export const ROUND_CARDS_AMOUNT = 4;

export const POKEAPI_URL = 'https://pokeapi.co/api/v2/pokemon/';

export const POKEMON_NAMES: readonly string[] = [
  'bulbasaur',
  'charmander',
  'squirtle',
  'caterpie',
  'pidgey',
  'rattata',
  'spearow',
  'ekans',
  'pikachu',
  'sandshrew',
  'clefairy',
  'vulpix',
  'jigglypuff',
  'zubat',
  'venonat',
  'diglett',
  'meowth',
  'psyduck',
  'mankey',
  'growlithe',
  'abra',
  'machop',
  'bellsprout',
  'geodude',
  'ponyta',
  'slowpoke',
  'magnemite',
  'seel',
  'marowak',
  'chansey',
  'horsea',
  'staryu',
  'eevee',
  'gastly',
  'hypno'
];
